// Server-side only — rendered via @react-pdf/renderer in the API route.
import {
  Document, Page, Text, View, StyleSheet, Font,
} from "@react-pdf/renderer";
import type { PriceBand, StoneInput } from "@/lib/types";
import { DISCLAIMER } from "@/lib/constants";

Font.register({
  family: "Oxygen",
  fonts: [
    { src: "https://fonts.gstatic.com/s/oxygen/v16/2sDfZG1Wl4Lcnbu6iQ.ttf", fontWeight: 400 },
    { src: "https://fonts.gstatic.com/s/oxygen/v16/2sDcZG1Wl4LcnbuCNWgDbw.ttf", fontWeight: 700 },
  ],
});

const s = StyleSheet.create({
  page:       { padding: 40, fontFamily: "Oxygen", backgroundColor: "#FFFFFF" },
  header:     { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 28 },
  brand:      { fontSize: 18, fontWeight: 700, color: "#111827" },
  accent:     { color: "#F59E0B" },
  tagline:    { fontSize: 8, color: "#6B7280", marginTop: 2 },
  sectionTitle: { fontSize: 10, fontWeight: 700, color: "#6B7280", textTransform: "uppercase", letterSpacing: 1, marginBottom: 8 },
  card:       { backgroundColor: "#F9FAFB", borderRadius: 8, padding: 16, marginBottom: 16 },
  row:        { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  label:      { fontSize: 9, color: "#6B7280" },
  value:      { fontSize: 9, fontWeight: 600, color: "#111827" },
  bandGrid:   { flexDirection: "row", gap: 8, marginBottom: 16 },
  bandCell:   { flex: 1, backgroundColor: "#FEF3C7", borderRadius: 6, padding: 12, alignItems: "center" },
  bandLabel:  { fontSize: 8, color: "#92400E", marginBottom: 4 },
  bandValue:  { fontSize: 16, fontWeight: 700, color: "#78350F" },
  bandSub:    { fontSize: 7, color: "#A16207", marginTop: 2 },
  disclaimer: { fontSize: 7, color: "#9CA3AF", lineHeight: 1.5, marginTop: 24, borderTopWidth: 1, borderTopColor: "#F3F4F6", paddingTop: 12 },
  footer:     { fontSize: 7, color: "#D1D5DB", marginTop: 8 },
});

function fmt(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
}

export function EstimatePDF({
  stone,
  band,
  modelVersion,
}: {
  stone: unknown;
  band: unknown;
  modelVersion: string;
}) {
  const s_ = stone as StoneInput;
  const b = band as PriceBand;
  const now = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  return (
    <Document title="DiamondPrice IQ Estimate" author="Centr8 LLP">
      <Page size="A4" style={s.page}>
        {/* Header */}
        <View style={s.header}>
          <View>
            <Text style={s.brand}>DiamondPrice<Text style={s.accent}> IQ</Text></Text>
            <Text style={s.tagline}>Fair-market diamond price estimate · {now}</Text>
          </View>
          <Text style={{ fontSize: 8, color: "#9CA3AF" }}>Model v{modelVersion}</Text>
        </View>

        {/* Stone details */}
        <Text style={s.sectionTitle}>Stone Details</Text>
        <View style={s.card}>
          {[
            ["Carat weight", `${s_.carat} ct`],
            ["Cut", s_.cut],
            ["Color", s_.color],
            ["Clarity", s_.clarity],
            ...(s_.shape ? [["Shape", s_.shape]] : []),
            ...(s_.fluorescence ? [["Fluorescence", s_.fluorescence]] : []),
            ...(s_.certificate ? [["Certificate", s_.certificate]] : []),
          ].map(([label, val]) => (
            <View key={label} style={s.row}>
              <Text style={s.label}>{label}</Text>
              <Text style={s.value}>{val}</Text>
            </View>
          ))}
        </View>

        {/* Price band */}
        <Text style={s.sectionTitle}>Estimated Price Range (USD)</Text>
        <View style={s.bandGrid}>
          {[
            { label: "Low (5th pct)", total: b.low, perCarat: b.per_carat_low },
            { label: "Median (50th pct)", total: b.mid, perCarat: b.per_carat_mid },
            { label: "High (95th pct)", total: b.high, perCarat: b.per_carat_high },
          ].map(({ label, total, perCarat }) => (
            <View key={label} style={s.bandCell}>
              <Text style={s.bandLabel}>{label}</Text>
              <Text style={s.bandValue}>{fmt(total)}</Text>
              <Text style={s.bandSub}>{fmt(perCarat)}/ct</Text>
            </View>
          ))}
        </View>

        {/* Disclaimer */}
        <Text style={s.disclaimer}>{DISCLAIMER}{"\n"}This report is generated from public listing data using a machine-learning model trained on ~50,000 diamond listings. It is not a certified appraisal and should not be used as the sole basis for any financial transaction. See diamondpriceiq.com/methodology for full details.</Text>
        <Text style={s.footer}>Generated by DiamondPrice IQ · Built by Centr8 LLP, Surat, India · diamondpriceiq.com</Text>
      </Page>
    </Document>
  );
}
